export const initialState = {
  conversion: {
    from: 'ETH',
    to: 'ETH',
    fromCurrency: [ 
    "TUSD",
    "KNC",
    "MANA",
    "SUSD",
    "LEND",
    "USDC",
    "SNX",
    "USDT",
    "REN",
    "ENJ",
    "BAT",
    "MKR",
    "ZRX",
    "BUSD",
    "REP",
    "LRC",
    "DAI",
    "LINK",
    "AUD",
    "OXT",
    "CHF",
    "BNT",
    "EUR",
    "JPY",
    "XHV",
    "GBP",
    "XAG",
    "XAU",
    
  ],
    toCurrency: ["BTC","ETH", "DAI", "USD", "USDT"],
  },
  console: [
    // {from: 'BTC', to: 'USDT', label: '24HOUR', value: '12345'},
    // {from: 'BTC', to: 'USDT', value: 'a->123'}
  ],
  arweave: {
    txData: {},
  },
  web3: null,
};
